name: "[1][UP] On Push"

on:
  push:
    branches: ["up"]
    paths: ["first/**"]
  workflow_dispatch:

jobs:
  echo-message:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
